slurmstepd: info: Setting TMPDIR to /scratch/13819. Previous errors about TMPDIR can be discarded
qmio-tools/0.1.1-python-3.9.9 unloaded
qmio-tools/0.1.1-python-3.9.9 loaded
gcccore/12.3.0 loaded
binutils/2.40 loaded
gcc/12.3.0 loaded
rust/1.75.0 loaded
cmake/3.27.6 loaded

imkl/2023.2.0 loaded
ninja/1.9.0 loaded
meson/1.4.0-python-3.9.9 loaded
meson-python/0.16.0-python-3.9.9 loaded
cython/3.0.9-python-3.9.9 loaded
numpy/1.26.4-python-3.9.9 loaded
pythran/0.15.0-python-3.9.9 loaded
pybind11/2.12.0-python-3.9.9 loaded
xsimd/12.1.1 loaded
scipy/1.13.0-python-3.9.9 loaded
llvm/16.0.0 loaded
gmp/6.1.2 unloaded
gmp/6.3.0 loaded
mpfr/4.2.1 loaded
mpc/1.3.1 loaded
flint/3.1.2 loaded
symengine/0.11.2 loaded
symengine-python/0.11.0-python-3.9.9 loaded
spdlog/1.9.2 loaded
pylatexenc/2.10-python-3.9.9 loaded
libgd/2.3.3 loaded
nasm/2.16.03 loaded
libjpeg-turbo/3.0.2 loaded
matplotlib/3.5.3-python-3.9.9 loaded
pandas/2.2.2-python-3.9.9 loaded
seaborn/0.12.2-python-3.9.9 loaded
qiskit/1.0.2-python-3.9.9 loaded
libffi/3.4.2 unloaded
libffi/3.4.2 loaded
python/3.9.9 unloaded
sqlite/3.45.3 loaded
python/3.9.9 loaded
qmio-tools/0.1.1-python-3.9.9 unloaded
qmio-tools/0.1.2-python-3.9.9 loaded

Due to MODULEPATH changes, the following have been reloaded:
  1) libffi/3.4.2     2) python/3.9.9

The following have been reloaded with a version change:
  1) gmp/6.1.2 => gmp/6.3.0
  2) qmio-tools/0.1.1-python-3.9.9 => qmio-tools/0.1.2-python-3.9.9



-------------PRUEBA VECTOR B-------------


[0.         0.26726792 0.53452917 0.80177704] 

Importing calibrations from  /opt/cesga/qmio/hpc/calibrations/2024_07_11__12_00_02.json
[0.62193269 0.75252747 0.21069217 0.05010937]
Traceback (most recent call last):
  File "/mnt/netapp2/Home_FT2/home/usc/ei/fft/CITMAGA/b_test.py", line 42, in <module>
    vect = ampl_from_sim(hhl.qc,backend,nb,4)
  File "/mnt/netapp2/Home_FT2/home/usc/ei/fft/CITMAGA/b_test.py", line 11, in ampl_from_sim
    job = backend.run(qc,shots=shots)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcc/12.3.0/qmio-tools/0.1.2-python-3.9.9/lib/python3.9/site-packages/qmiotools/integrations/qiskitqmio.py", line 432, in run
    raise QPUException(results["Exception"])
qmiotools.exceptions.QPUException: ValueError('Error playback time is greater than repetition period!Please increase repetition_period')
