slurmstepd: info: Setting TMPDIR to /scratch/13681. Previous errors about TMPDIR can be discarded
libffi/3.4.2 loaded
gmp/6.1.2 loaded
glpk/4.65 loaded
python/3.9.9 loaded
qmio-run/0.1.3-python-3.9.9 loaded
qmio-tools/0.1.1-python-3.9.9 loaded
gcccore/12.3.0 loaded
binutils/2.40 loaded
gcc/12.3.0 loaded
rust/1.75.0 loaded
cmake/3.27.6 loaded

imkl/2023.2.0 loaded
ninja/1.9.0 loaded
meson/1.4.0-python-3.9.9 loaded
meson-python/0.16.0-python-3.9.9 loaded
cython/3.0.9-python-3.9.9 loaded
numpy/1.26.4-python-3.9.9 loaded
pythran/0.15.0-python-3.9.9 loaded
pybind11/2.12.0-python-3.9.9 loaded
xsimd/12.1.1 loaded
scipy/1.13.0-python-3.9.9 loaded
llvm/16.0.0 loaded
gmp/6.1.2 unloaded
gmp/6.3.0 loaded
mpfr/4.2.1 loaded
mpc/1.3.1 loaded
flint/3.1.2 loaded
symengine/0.11.2 loaded
symengine-python/0.11.0-python-3.9.9 loaded
spdlog/1.9.2 loaded
pylatexenc/2.10-python-3.9.9 loaded
libgd/2.3.3 loaded
nasm/2.16.03 loaded
libjpeg-turbo/3.0.2 loaded
matplotlib/3.5.3-python-3.9.9 loaded
pandas/2.2.2-python-3.9.9 loaded
seaborn/0.12.2-python-3.9.9 loaded
qiskit/1.0.2-python-3.9.9 loaded
libffi/3.4.2 unloaded
libffi/3.4.2 loaded
python/3.9.9 unloaded
sqlite/3.45.3 loaded
python/3.9.9 loaded
qmio-tools/0.1.1-python-3.9.9 unloaded
qmio-tools/0.1.2-python-3.9.9 loaded

Due to MODULEPATH changes, the following have been reloaded:
  1) libffi/3.4.2     2) python/3.9.9

The following have been reloaded with a version change:
  1) gmp/6.1.2 => gmp/6.3.0
  2) qmio-tools/0.1.1-python-3.9.9 => qmio-tools/0.1.2-python-3.9.9

Importing calibrations from  /opt/cesga/qmio/hpc/calibrations/2024_07_09__12_00_01.json
Importing calibrations from  /opt/cesga/qmio/hpc/calibrations/2024_07_09__12_00_01.json
Traceback (most recent call last):
  File "/mnt/netapp2/Home_FT2/home/usc/ei/fft/CITMAGA/pruebas.py", line 173, in <module>
    results = hhl.get_counts(backend2,shots=8192)
  File "/mnt/netapp2/Home_FT2/home/usc/ei/fft/CITMAGA/hhl_functions.py", line 383, in get_counts
    plt.savefig('qc_meas.png')
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/pyplot.py", line 977, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 540, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 431, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 447, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/opt/cesga/qmio/hpc/software/Compiler/gcccore/12.3.0/matplotlib/3.5.3-python-3.9.9/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 93, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 2376x650945 pixels is too large. It must be less than 2^16 in each direction.
